# Generated by Django 5.2 on 2025-04-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_dis',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_document',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_edu',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_image',
        ),
    ]
